---
- name: Configure WCWC workstation - run ipa-client-install manually first
  hosts: workstations
  remote_user: root

  tasks:

    # this list is not minimal and combines needs of basic wcwc and the BNL WCWC clustering policy
    - name: Install WCWC workstation client packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - autofs
          - build-essential
          - ca-certificates
          - ccache
          - coreutils
          - curl
          - direnv
          - distcc
          - environment-modules
          - fd-find
          - fish
          - freeipa-client
          - gfortran
          - git
          - golang-go
          - gpg
          - ipython3
          - jupyter
          - keychain
          - kitty
          - lsb-release
          - nfs-kernel-server
          - podman
          - plocate
          - python-is-python3
          - python3
          - python3-click
          - python3-distutils
          - python3-matplotlib
          - python3-numpy
          - python3-pandas
          - python3-torch
          - python3-torchaudio
          - python3-torchtext
          - python3-torchvision
          - python3-venv
          - python3-yaml
          - ripgrep
          - rsync
          - screen
          - tcsh
          - tree
          - tmux
          - unzip
          - vim
          - xpra
          - zip

    - name: Provide auto_home.sh
      ansible.builtin.copy:
        src: auto_home.sh
        dest: /etc/auto_home.sh
        owner: root
        mode: '755'
        
    - name: Install wcwc command
      ansible.builtin.copy:
        src: ../../scripts/wcwc
        dest: /usr/local/bin/wcwc
        owner: root
        mode: '755'      
    - name: Hook direnv to shell
      ansible.builtin.lineinfile:
        path: /etc/profile.d/direnv.sh
        line: 'eval "$(direnv hook bash)"'
        create: true
    - name: Hook direnv to fish
      ansible.builtin.lineinfile:
        path: /etc/fish/conf.d/direnv.fish
        line: 'direnv hook fish | source'
        create: true
    - name: Hook direnv to tcsh
      ansible.builtin.lineinfile:
        path: /etc/csh/cshrc.d/direnv
        line: "eval `direnv hook tcsh`"
        create: true

        
