---
- name: Configure workstation to mount WCWC
  hosts: wcwc_nfs_mounters
  remote_user: root

  tasks:

    - name: Provide /wcwc as NFS mount
      when: wcwc_nfs_server is defined
      ansible.posix.mount:
        src: "{{wcwc_nfs_server}}:{{wcwc_path}}"
        path: "{{wcwc_path}}"
        opts: "ro,defaults,_netdev"
        state: mounted
        fstype: nfs

