---
- name: Configure WCWC workstation - run ipa-client-install manually first
  hosts: workstations
  remote_user: root

  tasks:

    # this list is not minimal and combines needs of basic wcwc and the BNL WCWC clustering policy
    - name: Install WCWC workstation client packages
      ansible.builtin.apt:
        pkg:
          - autofs
          - build-essential
          - ca-certificates
          - coreutils
          - curl
          - direnv
          - environment-modules
          - fish
          - freeipa-client
          - gfortran
          - git
          - gpg
          - keychain
          - lsb-release
          - nfs-kernel-server
          - python-is-python3
          - python3
          - python3-distutils
          - python3-venv
          - python3-click
          - python3-yaml
          - rsync
          - unzip
          - zip

    - name: Provide auto_home.sh
      ansible.builtin.copy:
        src: auto_home.sh
        dest: /etc/auto_home.sh
        owner: root
        mode: '755'
        
    - name: Install wcwc command
      ansible.builtin.copy:
        src: ../../scripts/wcwc
        dest: /usr/local/bin/wcwc
        owner: root
        mode: '755'      
