---
- name: Configure workstation to mount WCWC
  hosts: all_wcwc
  remote_user: root

  tasks:

    - name: Install WCWC workstation client packages
      ansible.builtin.apt:
        pkg:
          - build-essential
          - ca-certificates
          - coreutils
          - curl
          - environment-modules
          - gfortran
          - git
          - gpg
          - lsb-release
          - nfs-common
          - python3
          - python3-distutils
          - python3-venv
          - python3-click
          - unzip
          - zip

    - name: Assure {{wcwc_path}} directory
      action: file path={{wcwc_path}} state=directory
