# general user workstations that go all-in with features
workstations:
  hosts:
    hierocles.phy.bnl.gov:
    heracles.phy.bnl.gov:
    aswork.phy.bnl.gov:
    wcgpu0.phy.bnl.gov:
    wcgpu1.phy.bnl.gov:
  vars:
    ansible_remote_user: root

# systems providing some service
servers:
  hosts:
    lycastus.phy.bnl.gov:    

# all systems in the WCWC
all_wcwc:
  children:
    workstations:
    servers:
  vars:
    wcwc_path: /wcwc
    wcwc_lan: '130.199.22.0/23'

# automount /wcwc
wcwc_nfs_automounters:
  hosts:
    heracles.phy.bnl.gov:
    aswork.phy.bnl.gov:

# rsync /wcwc.  Before moving a host from automount to rsync be sure to REMOVE
# the automounting config.  Remove /etc/auto.wcwc,
# /etc/auto.master.d/wcwc.autofs, /etc/auto.direct and its line in
# /etc/auto.master and "service sssd restart" and "service autofs restart" and
# make sure "mount|grep wcwc" is clean.  Yes, this should all be ansiblized....
wcwc_rsyncers:
  hosts:
    hierocles.phy.bnl.gov:
    wcgpu0.phy.bnl.gov:
    wcgpu1.phy.bnl.gov:
    

# # workstations that nfs-mount /wcwc
# wcwc_nfs_mounters:
#   children:
#     workstations:
    

# systems providing /wcwc via NFS
wcwc_nfs_servers:
  hosts:
    lycastus.phy.bnl.gov:
  vars:
    wcwc_real_path: '/data1/wcwc'
    wcwc_path: '/wcwc'
    wcwc_lan: '130.199.22.0/23'

# possible todo:
# - indicate workstation owner username
# - expand to include non-BNL WCWC's
