#+title: Guidance on getting access to LLMs in BNL Azure
#+setupfile: wcwc-setup.org

BNL provides access to Microsoft Azure AI which includes many "top brand" LLMs
from OpenAI and Anthropic and others (but not Gemini) as well as a special
"model-router" deployment selects "most suitable" backend LLM by analyzing a
prompt.  The Azure AI provides both chat UI and API access.  This document
collects info to help others make use of this resource.

* BNL Azure access roles

Azure has a complex accounting system.  For this document we consider only two roles:

- subscriber :: The user has ability to make "deployments" and assumes cost management duties (charged to a BNL project/activity code).
- API-only :: The user is given an *API key* and *endpoint URL* for one or more LLM "deployments" by a subscriber.

If you want to be an API-only user, jump to section [[API Only]] to skip the laborious subscriber instructions.

** Subscriber access to BNL Azure

Gaining subscriber access is somewhat involved.  API-only access is fairly
trivial but requires someone to serve you as a subscriber.  A group may want to
start with just one user providing the subscriber duties.

*** Requesting a subscriber account

This guidance is as of 2026-01-01 and may have changed.

- A user contacts ITD requesting a *subscriber account* to BNL Azure

- ITD will give user a customized web form to fill out.

- The form lists and links additional requests that must be made.  

  - Two-factor authentication :: The form lists Microsoft Authenticator movile
    application and Yubikey but not DUO.  Microsoft Authenticator is not
    required at least if Yubikey is used.  During the onbording process, DUO is
    also offered and it may be possible to use that instead of Yubikey.

  - Microsoft Office365 account :: A new Microsoft Office365 account is required
    in addition to an existing the "BNL Domain" account.  The new account name
    seems to be chosen with "365" appended to the BNL Domain account.

After submitting the form and after obtaining the new Microsoft Office365
account, you will get an email from ITD with initial Azure onboarding
instructions and an initial password encrypted for your existing Microsoft
Office365 account.

If the decrypt link does not work, try to log in to https://portal.office.com/
using your BNL Domain account.

Once the initial password is plain text, log into
https://myprofile.microsoft.com and set up two-factor authentication.  Note,
"FIDO2" means Yubikey.

Once the new account is all settled, one more loop with ITD is needed to get access to Azure.  You can then log in to https://portal.azure.com/ and deploy models.

*** Deploying a model in Azure

To use an LLM one makes a "deployment" in a "foundry".

1. Sign in to https://ai.azure.com/ with your new Office365 account.
2. If not already, create a new "foundry" (slide box at top of page).
3. Pick a model and "deploy" it with the deploy button. 
4. From the deployed model chat UI you can get API key and endpoint

The endpoint is a URL like:

   https://USERNAME-ID-resource.services.ai.azure.com/api/projects/USERNAME-ID

This URL may be more specific than needed to access the API.


*** Linking subscriber accounts

It is possible to have one subscriber account linked to another so that only one
deals with billing issues while both may perform deployments.

Details t.b.d.

** API Only

Ask a subscriber for an "endpoint URL" and "API key".

The URL you will be given is typically not exactly in a the form required by
your API client but it will include salient parts.  In general, Azure endpoint
URLs will have three parts to set properly.

#+begin_example
https://{resource}.{domain}/{path}
#+end_example

- resource :: this typically includes the subscriber user ID plus some other text and it names a set of "deployments".  You will typically keep the *resource* string as-is when configuring your API client.  Some clients need be given only the *resource* string and not a full URL.
- domain :: this may be =openai.azure.com=, =services.ai.azure.com= or something else.  You may need to use totally different domains for a given client and depending on the LLM model in the "deployment".  Some clients may want to switch the domain depending on the LLM (eg, OpenAI compatible access vs other).
- path :: the exact path to use may differ from what is provided and depend on the client, the LLM to access (again, OpenAI vs other) or other things.


* Configuring client to use Azure AI

** Aider

Aider needs 3 shell environment variables to use Azure AI:

#+begin_example
$ export AZURE_API_VERSION=2024-12-01-preview
$ export AZURE_API_KEY=KEY
$ export AZURE_API_BASE=https://RESOURCE.services.ai.azure.com
#+end_example

- version :: This is a magic value.  
- key :: The API key
- base :: The shortened endpoint URL

#+begin_note
I do not know how to get a correct *version* in general.  Please let me know if you do.  Both *key* and *base* info is available to the subscriber from, eg, the chat UI for the deployment.  Note, the *base* URL is shorter than the presented endpoint URL.
#+end_note

*** Anthropic models and aider

Azure supplies models from Anthropic but I am unable to talk with them as of
aider 0.86.1.  However, using the =anthropic.AnthropicFoundry= Python class and
the above =AZURE= info, can establish connection and get a response to a prompt.
I suspect there is a problem in lightlm bundled with aider related to the
construction of the API URL.

** Claude Code

The subscriber may deploy models from Anthropic and these can be accessed via Claude Code with the following environment varialbes

#+begin_example
$ export CLAUDE_CODE_USE_FOUNDRY=1
$ export ANTHROPIC_FOUNDRY_API_KEY=KEY
$ export ANTHROPIC_FOUNDRY_RESOURCE=RESOURCE 
$ claude
#+end_example

Here, =RESOURCE= is just the "host name" in the Azure AI endpoint URL and not the entire URL.

Note, when starting =claude=, you should not be asked to select an Anthropic account access.  If you are, it likely means ~CLAUDE_CODE_USE_FOUNDRY=1~ was not set.

More config info at https://code.claude.com/docs/en/model-config

*** Claude code with OpenAI model deployments

t.b.d.  Some say it is possible, some say it is not.

** Codex CLI

t.b.d.

** Gemini CLI

Currently not applicable to Azure.

* Appendix 

** Azure glossary

Please contact the author with any additions and corrections.

- api key :: Azure API keys are 84 character strings
- endpoint :: an API URL which may or may not be fully in a form ready to use by an API client
- resource :: a unit of accounting (aka "resource group"?)
- deployment :: an instance of an LLM often but not necessarily taking the same name as the deployed model.
- foundry :: or "AI foundry" a unit in which deployments are made and served.
- subscriber :: the account that pays the bills and makes the deployments

** A note on API key security

The API key and resource name are the only "secrets" needed to incur potentially
substantial costs.  Do not commit these secrets into repos or otherwise make
them public unless you are prepared to pay for the entire Internet to use the
service.

A good way to assure this is to keep the API key and resource encrypted at rest
in password store and transfer it to environment variables in a way that no
plain-text file is involved.

For a home-grown mechanism to do this, see https://github.com/brettviren/passdb
